#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Will proceed to check code format and lint! 😁'

npm run format || (
    echo 'Issues with code formatting! Please use Prettier and refer to above errors! 🚫'
    false;
)

echo 'Code has no formatting issues! ✅'

npm run eslint || (
    echo 'Issues with code linting! Please use ESLint! and refer to above errors! 🚫'
    false;
)

echo 'Code has no linting issues! ✅'